using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class AdvancedScenarioTests
{
    [Fact]
    public void ComplexScenario_AllFeaturesCombined()
    {
        const string code = """
                            #nullable enable
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            [NotifyPropertyChanged(true)]
                            [NotifyPropertyChanging(true)]
                            public partial class ComplexScenario
                            {
                                private bool GuardMethod(int oldValue, int newValue) => newValue > 0;

                                [VirtualProperty]
                                [PropertyEncapsulation(EPropertyEncapsulation.Protected)]
                                [ValidationStrategy(EValidationStrategy.Exception)]
                                [Range(1, 100)]
                                [Guard(nameof(GuardMethod))]
                                [PropertyName("Age")]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class ComplexScenario
                                 : System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging
                                {
                                    public event System.ComponentModel.PropertyChangingEventHandler? PropertyChanging;
                                    public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
                                    [System.ComponentModel.DataAnnotations.RangeAttribute(1, 100)]
                                    protected virtual int Age
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (value < 1 || value > 100)
                                                throw new System.ArgumentException("Validation of Age failed: Value must be between 1 and 100", nameof(value));
                                            if (!GuardMethod(_field, value))
                                                throw new System.ArgumentException("Validation of Age failed: Guard method GuardMethod failed", nameof(value));
                                            this.PropertyChanging?.Invoke(this, new System.ComponentModel.PropertyChangingEventArgs("Age"));
                                            _field = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Age"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("ComplexScenario", code, expected);
    }

    [Fact]
    public void EmptyClass_WithGeneratePropertiesAttribute_GeneratesEmptyPartial()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class EmptyClass
                            {
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class EmptyClass
                                {
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("EmptyClass", code, expected);
    }

    [Fact]
    public void EqualityCheckNone_WithNotifyPropertyChanged_SkipsEqualityButNotifies()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [NotifyPropertyChanged(true)]
                            public partial class EqualityCheckNoneWithNotification
                            {
                                [EqualityCheck(EEqualityCheckMode.None)]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class EqualityCheckNoneWithNotification
                                 : System.ComponentModel.INotifyPropertyChanged
                                {
                                    public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            _field = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("EqualityCheckNoneWithNotification", code, expected);
    }

}
