using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class AttributeTests
{
    [Fact]
    public void PropertyAttributeOnClass_AppliesAttributesToAllProperties()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            [PropertyAttribute("System.ComponentModel.DataAnnotations.Range(5, 6), System.ComponentModel.DataAnnotations.MaxLength(123)")]
                            public partial class PropertyAttributeAttributeOnClass
                            {
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class PropertyAttributeAttributeOnClass
                                {
                                    [System.ComponentModel.DataAnnotations.Range(5, 6), System.ComponentModel.DataAnnotations.MaxLength(123)]
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PropertyAttributeAttributeOnClass", code, expected);
    }

    [Fact]
    public void PropertyAttributeOnField_AppliesAttributeToSingleProperty()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class PropertyAttributeAttributeOnField
                            {
                                [PropertyAttribute("System.ComponentModel.DataAnnotations.Range(5, 6), System.ComponentModel.DataAnnotations.MaxLength(123)")]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class PropertyAttributeAttributeOnField
                                {
                                    [System.ComponentModel.DataAnnotations.Range(5, 6), System.ComponentModel.DataAnnotations.MaxLength(123)]
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PropertyAttributeAttributeOnField", code, expected);
    }

    [Fact]
    public void PropertyAttributeOnClassAndField_CanInherit()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            [PropertyAttribute("System.ComponentModel.DataAnnotations.MaxLength(123)")]
                            public partial class PropertyAttributeAttributeOnClassAndField
                            {
                                [PropertyAttribute("System.ComponentModel.DataAnnotations.Range(7, 8)")]
                                private int _field1;

                                [PropertyAttribute("System.ComponentModel.DataAnnotations.Range(7, 8)", inherit: true)]
                                private int _field2;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class PropertyAttributeAttributeOnClassAndField
                                {
                                    [System.ComponentModel.DataAnnotations.Range(7, 8)]
                                    public int Field1
                                    {
                                        get => _field1;
                                        set
                                        {
                                            if (value.Equals(_field1)) return;
                                            _field1 = value;
                                        }
                                    }
                                    [System.ComponentModel.DataAnnotations.Range(7, 8)]
                                    [System.ComponentModel.DataAnnotations.MaxLength(123)]
                                    public int Field2
                                    {
                                        get => _field2;
                                        set
                                        {
                                            if (value.Equals(_field2)) return;
                                            _field2 = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PropertyAttributeAttributeOnClassAndField", code, expected);
    }

    [Fact]
    public void DisableAttributeTakeoverOnClass_DisablesAttributeCopying()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            [DisableAttributeTakeover]
                            public partial class WithDisableAttributeTakeoverOnClass
                            {
                                [Range(5, 6)]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class WithDisableAttributeTakeoverOnClass
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (value < 5 || value > 6)
                                                throw new System.ArgumentException("Validation of Field failed: Value must be between 5 and 6", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("WithDisableAttributeTakeoverOnClass", code, expected);
    }

    [Fact]
    public void DisableAttributeTakeoverOnField_DisablesForSpecificField()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class WithDisableAttributeTakeoverOnField
                            {
                                [DisableAttributeTakeover]
                                [Range(5, 6)]
                                private int _field1;

                                [Range(5, 6)]
                                private int _field2;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class WithDisableAttributeTakeoverOnField
                                {
                                    public int Field1
                                    {
                                        get => _field1;
                                        set
                                        {
                                            if (value.Equals(_field1)) return;
                                            if (value < 5 || value > 6)
                                                throw new System.ArgumentException("Validation of Field1 failed: Value must be between 5 and 6", nameof(value));
                                            _field1 = value;
                                        }
                                    }
                                    [System.ComponentModel.DataAnnotations.RangeAttribute(5, 6)]
                                    public int Field2
                                    {
                                        get => _field2;
                                        set
                                        {
                                            if (value.Equals(_field2)) return;
                                            if (value < 5 || value > 6)
                                                throw new System.ArgumentException("Validation of Field2 failed: Value must be between 5 and 6", nameof(value));
                                            _field2 = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("WithDisableAttributeTakeoverOnField", code, expected);
    }

    [Fact]
    public void WithoutDisableAttributeTakeover_CopiesAttributes()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class WithoutDisableAttributeTakeoverOnField
                            {
                                [Range(5, 6)]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class WithoutDisableAttributeTakeoverOnField
                                {
                                    [System.ComponentModel.DataAnnotations.RangeAttribute(5, 6)]
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (value < 5 || value > 6)
                                                throw new System.ArgumentException("Validation of Field failed: Value must be between 5 and 6", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("WithoutDisableAttributeTakeoverOnField", code, expected);
    }
}
