using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class BasicPropertyGenerationTests
{
    [Fact]
    public void GeneratePropertiesOnClass_GeneratesProperty()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class GeneratePropertiesOnClass
                            {
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class GeneratePropertiesOnClass
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("GeneratePropertiesOnClass", code, expected);
    }

    [Fact]
    public void GeneratePropertiesOnField_GeneratesProperty()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class GeneratePropertiesOnField
                            {
                                [GenerateProperties]
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class GeneratePropertiesOnField
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("GeneratePropertiesOnField", code, expected);
    }

    [Fact]
    public void PropertiesBackingFieldIsLeftUnaffected_WhenPropertyExists()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class PropertiesBackingFieldIsLeftUnaffected
                            {
                                private float _field;

                                public bool Test { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class PropertiesBackingFieldIsLeftUnaffected
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PropertiesBackingFieldIsLeftUnaffected", code, expected);
    }

    [Fact]
    public void PropertyName_OverridesDefaultName()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class PropertyName
                            {
                                [PropertyName("SomeName")]
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class PropertyName
                                {
                                    public float SomeName
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PropertyName", code, expected);
    }

    [Fact]
    public void DocumentationTakeover_PreservesXmlDocumentation()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class DocumentationTakeover
                            {
                                /// <summary>
                                /// This is a documentation comment.
                                /// </summary>
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class DocumentationTakeover
                                {
                                    /// <summary>
                                    /// This is a documentation comment.
                                    /// </summary>
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("DocumentationTakeover", code, expected);
    }

    [Fact]
    public void NoPropertyAttribute_SkipsPropertyGeneration()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class NoPropertyAttributeOnField
                            {
                                private int _field1;
                                [NoProperty]
                                private int _field2;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class NoPropertyAttributeOnField
                                {
                                    public int Field1
                                    {
                                        get => _field1;
                                        set
                                        {
                                            if (value.Equals(_field1)) return;
                                            _field1 = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NoPropertyAttributeOnField", code, expected);
    }

    [Fact]
    public void ConstFieldIsIgnored_DoesNotGenerateProperty()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class ConstFieldIsIgnored
                            {
                                [GenerateProperties]
                                private int _field1;
                                [GenerateProperties]
                                private const int ConstantValue = 1;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class ConstFieldIsIgnored
                                {
                                    public int Field1
                                    {
                                        get => _field1;
                                        set
                                        {
                                            if (value.Equals(_field1)) return;
                                            _field1 = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("ConstFieldIsIgnored", code, expected);
    }
}
