using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class DefaultValueTests
{
    [Fact]
    public void DefaultValueAsString_OnPartialProperty_GeneratesCorrectExpression()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class TestClass
                            {
                                [DefaultValueAsString("new object()")]
                                public partial object MyObject { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class TestClass
                                {
                                    private object? ___myObject = new object();
                                    public partial object? MyObject
                                    {
                                        get => ___myObject;
                                        set
                                        {
                                            if (value is null && ___myObject is null || (value?.Equals(___myObject) ?? false)) return;
                                            ___myObject = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("TestClass", code, expected);
    }
}
