using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class EqualityCheckTests
{
    [Fact]
    public void EqualityCheckDefault_UsesEqualsMethod()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class EqualityCheckDefault
                            {
                                [EqualityCheck(EEqualityCheckMode.Default)]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class EqualityCheckDefault
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("EqualityCheckDefault", code, expected);
    }

    [Fact]
    public void EqualityCheckCustom_UsesCustomMethod()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class EqualityCheckCustom
                            {
                                private static bool CustomEqualityCheck(int oldValue, int newValue) => false;
                                [EqualityCheck(EEqualityCheckMode.Custom, custom: nameof(CustomEqualityCheck))]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class EqualityCheckCustom
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (CustomEqualityCheck(_field, value)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("EqualityCheckCustom", code, expected);
    }

    [Fact]
    public void EqualityCheckNone_SkipsEqualityCheck()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class EqualityCheckNone
                            {
                                [EqualityCheck(EEqualityCheckMode.None)]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class EqualityCheckNone
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("EqualityCheckNone", code, expected);
    }
}
