using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class GuardMethodTests
{
    [Fact]
    public void SingleGuard_GeneratesGuardCheck()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class SingleGuard
                            {
                                private bool GuardMethod(int oldValue, int newValue) => true;
                                [Guard(nameof(GuardMethod))]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class SingleGuard
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (!GuardMethod(_field, value))
                                                throw new System.ArgumentException("Validation of Field failed: Guard method GuardMethod failed", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("SingleGuard", code, expected);
    }

    [Fact]
    public void MultipleGuards_GeneratesMultipleChecks()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class MultipleGuards
                            {
                                private bool GuardMethod1(int oldValue, int newValue) => true;
                                private bool GuardMethod2(int oldValue, int newValue) => true;
                                [Guard(nameof(GuardMethod1)), Guard(nameof(GuardMethod2))]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class MultipleGuards
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (!GuardMethod1(_field, value))
                                                throw new System.ArgumentException("Validation of Field failed: Guard method GuardMethod1 failed", nameof(value));
                                            if (!GuardMethod2(_field, value))
                                                throw new System.ArgumentException("Validation of Field failed: Guard method GuardMethod2 failed", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("MultipleGuards", code, expected);
    }

    [Fact]
    public void GuardNoOldValue_OmitsOldValue()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class GuardNoOldValue
                            {
                                private bool GuardMethod(int newValue) => true;
                                [Guard(nameof(GuardMethod), HasOldValue = false)]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class GuardNoOldValue
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (!GuardMethod(value))
                                                throw new System.ArgumentException("Validation of Field failed: Guard method GuardMethod failed", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("GuardNoOldValue", code, expected);
    }

    [Fact]
    public void GuardNoOldNoNewValue_OmitsBothValues()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class GuardNoOldNoNewValue
                            {
                                private bool GuardMethod() => true;
                                [Guard(nameof(GuardMethod), HasOldValue = false, HasNewValue = false)]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class GuardNoOldNoNewValue
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (!GuardMethod())
                                                throw new System.ArgumentException("Validation of Field failed: Guard method GuardMethod failed", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("GuardNoOldNoNewValue", code, expected);
    }

    [Fact]
    public void GuardNoNewValue_OmitsNewValue()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class GuardNoNewValue
                            {
                                private bool GuardMethod(int oldValue) => true;
                                [Guard(nameof(GuardMethod), HasOldValue = true, HasNewValue = false)]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class GuardNoNewValue
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (!GuardMethod(_field))
                                                throw new System.ArgumentException("Validation of Field failed: Guard method GuardMethod failed", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("GuardNoNewValue", code, expected);
    }

    [Fact]
    public void GuardAdditionalArguments_PassesExtraArguments()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class GuardAdditionalArguments
                            {
                                private bool GuardMethod(int oldValue, int newValue, int arg1, string arg2, bool arg3, string[] arg4) => true;
                                [Guard(nameof(GuardMethod), Arguments = new object[] { 1, "test", true, new string[] { "a", "b" } })]
                                private int _field;
                            }
                            """;

        const string expected = """"
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class GuardAdditionalArguments
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (!GuardMethod(_field, value, 1, "test", true, new string[] { "a", "b" }))
                                                throw new System.ArgumentException("""Validation of Field failed: Guard method GuardMethod with arguments [1, "test", true, new string[] { "a", "b" }] failed""", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """";

        GeneratorTestHelper.VerifyGeneratedCode("GuardAdditionalArguments", code, expected);
    }

    [Fact]
    public void ValidationStrategyExceptionWithGuard_ThrowsException()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class ValidationStrategyExceptionWithGuard
                            {
                                private bool GuardMethod(int oldValue, int newValue) => true;
                                [ValidationStrategy(EValidationStrategy.Exception), Guard(nameof(GuardMethod))]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class ValidationStrategyExceptionWithGuard
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (!GuardMethod(_field, value))
                                                throw new System.ArgumentException("Validation of Field failed: Guard method GuardMethod failed", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("ValidationStrategyExceptionWithGuard", code, expected);
    }

    [Fact]
    public void ValidationStrategyRollbackWithGuardAndNotifyPropertyChanged_RollsBackWithNotification()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class ValidationStrategyRollbackWithGuardAndNotifyPropertyChanged : System.ComponentModel.INotifyPropertyChanged
                            {
                                public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

                                private bool GuardMethod(int oldValue, int newValue) => true;
                                [ValidationStrategy(EValidationStrategy.Rollback), Guard(nameof(GuardMethod)), NotifyPropertyChanged]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class ValidationStrategyRollbackWithGuardAndNotifyPropertyChanged
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (!GuardMethod(_field, value))
                                            {
                                                this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field"));
                                                return;
                                            }
                                            _field = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("ValidationStrategyRollbackWithGuardAndNotifyPropertyChanged", code, expected);
    }

    [Fact]
    public void ValidationStrategyIgnoreWithGuardAndNotifyPropertyChanged_IgnoresFailure()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class ValidationStrategyIgnoreWithGuardAndNotifyPropertyChanged : System.ComponentModel.INotifyPropertyChanged
                            {
                                public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

                                private bool GuardMethod(int oldValue, int newValue) => true;
                                [ValidationStrategy(EValidationStrategy.Ignore), Guard(nameof(GuardMethod)), NotifyPropertyChanged]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class ValidationStrategyIgnoreWithGuardAndNotifyPropertyChanged
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (!GuardMethod(_field, value))
                                                return;
                                            _field = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("ValidationStrategyIgnoreWithGuardAndNotifyPropertyChanged", code, expected);
    }

    [Fact]
    public void ValidationStrategyExceptionWithGuardAndNotifyPropertyChanged_ThrowsAndNotifies()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class ValidationStrategyExceptionWithGuardAndNotifyPropertyChanged : System.ComponentModel.INotifyPropertyChanged
                            {
                                public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

                                private bool GuardMethod(int oldValue, int newValue) => true;
                                [ValidationStrategy(EValidationStrategy.Exception), Guard(nameof(GuardMethod)), NotifyPropertyChanged]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class ValidationStrategyExceptionWithGuardAndNotifyPropertyChanged
                                {
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (!GuardMethod(_field, value))
                                                throw new System.ArgumentException("Validation of Field failed: Guard method GuardMethod failed", nameof(value));
                                            _field = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("ValidationStrategyExceptionWithGuardAndNotifyPropertyChanged", code, expected);
    }
}
