using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class NotificationTests
{
    [Fact]
    public void NotifyPropertyChangedOnAllWithGeneration_ImplementsInterface()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [NotifyPropertyChanged(true)]
                            public partial class NotifyPropertyChangedOnAllWithGeneration
                            {
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NotifyPropertyChangedOnAllWithGeneration
                                 : System.ComponentModel.INotifyPropertyChanged
                                {
                                    public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NotifyPropertyChangedOnAllWithGeneration", code, expected);
    }

    [Fact]
    public void NotifyPropertyChangedOnAllDefaultGeneration_ImplementsInterface()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [NotifyPropertyChanged]
                            public partial class NotifyPropertyChangedOnAllDefaultGeneration
                            {
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NotifyPropertyChangedOnAllDefaultGeneration
                                 : System.ComponentModel.INotifyPropertyChanged
                                {
                                    public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NotifyPropertyChangedOnAllDefaultGeneration", code, expected);
    }

    [Fact]
    public void NotifyPropertyChangedOnAllNoGeneration_DoesNotGenerateInterface()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [NotifyPropertyChanged(false)]
                            public partial class NotifyPropertyChangedOnAllNoGeneration
                            : System.ComponentModel.INotifyPropertyChanged
                            {
                                public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NotifyPropertyChangedOnAllNoGeneration
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NotifyPropertyChangedOnAllNoGeneration", code, expected);
    }

    [Fact]
    public void NotifyPropertyChangedOnField_NotifiesForSingleField()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class NotifyPropertyChangedOnField : System.ComponentModel.INotifyPropertyChanged
                            {
                                public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

                                [NotifyPropertyChanged]
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NotifyPropertyChangedOnField
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NotifyPropertyChangedOnField", code, expected);
    }

    [Fact]
    public void NotifyPropertyChangedWithMethod_UsesCustomMethod()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [NotifyPropertyChanged(false, "OnPropertyChanged")]
                            public partial class NotifyPropertyChangedWithMethodCode : System.ComponentModel.INotifyPropertyChanged
                            {
                                public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
                                protected void OnPropertyChanged(object sender, string propertyName)
                                {
                                    this.PropertyChanged?.Invoke(sender, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                                }

                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NotifyPropertyChangedWithMethodCode
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                            this.OnPropertyChanged(this, "Field");
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NotifyPropertyChangedWithMethodCode", code, expected);
    }

    [Fact]
    public void NotifyPropertyChangingOnAllWithGeneration_ImplementsInterface()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [NotifyPropertyChanging(true)]
                            public partial class NotifyPropertyChangingOnAllWithGeneration
                            {
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NotifyPropertyChangingOnAllWithGeneration
                                 : System.ComponentModel.INotifyPropertyChanging
                                {
                                    public event System.ComponentModel.PropertyChangingEventHandler? PropertyChanging;
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            this.PropertyChanging?.Invoke(this, new System.ComponentModel.PropertyChangingEventArgs("Field"));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NotifyPropertyChangingOnAllWithGeneration", code, expected);
    }

    [Fact]
    public void NotifyPropertyChangingOnAllDefaultGeneration_ImplementsInterface()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [NotifyPropertyChanging]
                            public partial class NotifyPropertyChangingOnAllDefaultGeneration
                            {
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NotifyPropertyChangingOnAllDefaultGeneration
                                 : System.ComponentModel.INotifyPropertyChanging
                                {
                                    public event System.ComponentModel.PropertyChangingEventHandler? PropertyChanging;
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            this.PropertyChanging?.Invoke(this, new System.ComponentModel.PropertyChangingEventArgs("Field"));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NotifyPropertyChangingOnAllDefaultGeneration", code, expected);
    }

    [Fact]
    public void NotifyPropertyChangingOnAllNoGeneration_DoesNotGenerateInterface()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [NotifyPropertyChanging(false)]
                            public partial class NotifyPropertyChangingOnAllNoGeneration
                            : System.ComponentModel.INotifyPropertyChanging
                            {
                                public event System.ComponentModel.PropertyChangingEventHandler? PropertyChanging;
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NotifyPropertyChangingOnAllNoGeneration
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            this.PropertyChanging?.Invoke(this, new System.ComponentModel.PropertyChangingEventArgs("Field"));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NotifyPropertyChangingOnAllNoGeneration", code, expected);
    }

    [Fact]
    public void NotifyPropertyChangingOnField_NotifiesForSingleField()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class NotifyPropertyChangingOnField : System.ComponentModel.INotifyPropertyChanging
                            {
                                public event System.ComponentModel.PropertyChangingEventHandler? PropertyChanging;

                                [NotifyPropertyChanging]
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NotifyPropertyChangingOnField
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            this.PropertyChanging?.Invoke(this, new System.ComponentModel.PropertyChangingEventArgs("Field"));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NotifyPropertyChangingOnField", code, expected);
    }

    [Fact]
    public void NotifyOn_NotifiesMultipleProperties()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [NotifyPropertyChanging(true)]
                            [NotifyPropertyChanged(true)]
                            public partial class NotifyOn
                            {
                                private float _field;
                                [NotifyOn(nameof(Field))]
                                public float Indicection => _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NotifyOn
                                 : System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging
                                {
                                    public event System.ComponentModel.PropertyChangingEventHandler? PropertyChanging;
                                    public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            this.PropertyChanging?.Invoke(this, new System.ComponentModel.PropertyChangingEventArgs("Field"));
                                            this.PropertyChanging?.Invoke(this, new System.ComponentModel.PropertyChangingEventArgs("Indicection"));
                                            _field = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field"));
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Indicection"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NotifyOn", code, expected);
    }

    [Fact]
    public void NotifyPropertyChangedWithGenericClass_HandlesGenerics()
    {
        const string code = """
                            #nullable enable
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [NotifyPropertyChanged(true)]
                            public partial class NotifyPropertyChangedWithGenericClass<TClass, TStruct>
                                where TClass : class
                                where TStruct : struct
                            {
                                private TClass _field1;
                                private string? _field2;
                                private string _field3;
                                private TStruct _field4;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NotifyPropertyChangedWithGenericClass<TClass, TStruct>
                                 : System.ComponentModel.INotifyPropertyChanged
                                {
                                    public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
                                    public TClass Field1
                                    {
                                        get => _field1;
                                        set
                                        {
                                            if (value.Equals(_field1)) return;
                                            _field1 = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field1"));
                                        }
                                    }
                                    public string? Field2
                                    {
                                        get => _field2;
                                        set
                                        {
                                            if (value is null && _field2 is null || (value?.Equals(_field2) ?? false)) return;
                                            _field2 = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field2"));
                                        }
                                    }
                                    public string Field3
                                    {
                                        get => _field3;
                                        set
                                        {
                                            if (value.Equals(_field3)) return;
                                            _field3 = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field3"));
                                        }
                                    }
                                    public TStruct Field4
                                    {
                                        get => _field4;
                                        set
                                        {
                                            if (value.Equals(_field4)) return;
                                            _field4 = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field4"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NotifyPropertyChangedWithGenericClass_TClass_TStruct_", code, expected);
    }
}
