using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class NullableHandlingTests
{
    [Fact]
    public void NullableEnabled_GeneratesNullableAwareEquality()
    {
        const string code = """
                            #nullable enable
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class NullableHandling
                            {
                                private string _notNullable;
                                private string? _nullable;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NullableHandling
                                {
                                    public string NotNullable
                                    {
                                        get => _notNullable;
                                        set
                                        {
                                            if (value.Equals(_notNullable)) return;
                                            _notNullable = value;
                                        }
                                    }
                                    public string? Nullable
                                    {
                                        get => _nullable;
                                        set
                                        {
                                            if (value is null && _nullable is null || (value?.Equals(_nullable) ?? false)) return;
                                            _nullable = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NullableHandling", code, expected);
    }

    [Fact]
    public void NullableDisabled_TreatsAllTypesAsNullable()
    {
        const string code = """
                            #nullable disable
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class NullableDisabled
                            {
                                private string _nullable;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class NullableDisabled
                                {
                                    public string? Nullable
                                    {
                                        get => _nullable;
                                        set
                                        {
                                            if (value is null && _nullable is null || (value?.Equals(_nullable) ?? false)) return;
                                            _nullable = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("NullableDisabled", code, expected);
    }
}
