using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class PartialPropertyTests
{
    
    [Fact]
    public void BadPartialPropertyWithDefaultValue_DoesNotCrashTheGenerator()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class PartialPropertyWithDefaultValue
                            {
                            [DefaultValue<string>("")]
                            public partial string PartialProperty { get; set; }
                            [DefaultValue<string>()]
                            public partial string IncorrectPartialProperty { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class PartialPropertyWithDefaultValue
                                {
                                    private string? ___partialProperty = "";
                                    public partial string? PartialProperty
                                    {
                                        get => ___partialProperty;
                                        set
                                        {
                                            if (value is null && ___partialProperty is null || (value?.Equals(___partialProperty) ?? false)) return;
                                            ___partialProperty = value;
                                        }
                                    }
                                    private string? ___incorrectPartialProperty;
                                    public partial string? IncorrectPartialProperty
                                    {
                                        get => ___incorrectPartialProperty;
                                        set
                                        {
                                            if (value is null && ___incorrectPartialProperty is null || (value?.Equals(___incorrectPartialProperty) ?? false)) return;
                                            ___incorrectPartialProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PartialPropertyWithDefaultValue", code, expected, [(8,2,"CS7036")]);
    }

    [Fact]
    public void RobustnessTest_RangeAttribute_MissingArguments_DoesNotCrash()
    {
        const string code = """
                            using System.ComponentModel.DataAnnotations;
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class TestClass
                            {
                                [Range]
                                [GenerateProperties]
                                private int _myProperty;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using System.ComponentModel.DataAnnotations;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class TestClass
                                {
                                    [System.ComponentModel.DataAnnotations.RangeAttribute]
                                    public int MyProperty
                                    {
                                        get => _myProperty;
                                        set
                                        {
                                            if (value.Equals(_myProperty)) return;
                                            _myProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("TestClass", code, expected, [(11, 6, "CS1729"), (7, 6, "CS1729")]);
    }

    [Fact]
    public void RobustnessTest_MaxLengthAttribute_MissingArguments_DoesNotCrash()
    {
        const string code = """
                            using System.ComponentModel.DataAnnotations;
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class TestClass
                            {
                                [MaxLength]
                                [GenerateProperties]
                                private string _myProperty;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using System.ComponentModel.DataAnnotations;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class TestClass
                                {
                                    [System.ComponentModel.DataAnnotations.MaxLengthAttribute]
                                    public string? MyProperty
                                    {
                                        get => _myProperty;
                                        set
                                        {
                                            if (value is null && _myProperty is null || (value?.Equals(_myProperty) ?? false)) return;
                                            _myProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("TestClass", code, expected, [(7, 6, "CS7036"), (12, 6, "CS7036")]);
    }

    [Fact]
    public void RobustnessTest_GetterSetterAttributes_MissingArguments_DoesNotCrash()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class TestClass
                            {
                                [Getter]
                                [Setter]
                                [GenerateProperties]
                                private int _myProperty;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class TestClass
                                {
                                    public int MyProperty
                                    {
                                        get => _myProperty;
                                        set
                                        {
                                            if (value.Equals(_myProperty)) return;
                                            _myProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("TestClass", code, expected, [(6, 6, "CS7036"), (7, 6, "CS7036")]);
    }

    [Fact]
    public void RobustnessTest_NotifyAttributes_MissingArguments_DoesNotCrash()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [NotifyPropertyChanged]
                            [NotifyPropertyChanging]
                            public partial class TestClass
                            {
                                [GenerateProperties]
                                private int _myProperty;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class TestClass
                                 : System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging
                                {
                                    public event System.ComponentModel.PropertyChangingEventHandler? PropertyChanging;
                                    public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
                                    public int MyProperty
                                    {
                                        get => _myProperty;
                                        set
                                        {
                                            if (value.Equals(_myProperty)) return;
                                            this.PropertyChanging?.Invoke(this, new System.ComponentModel.PropertyChangingEventArgs("MyProperty"));
                                            _myProperty = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("MyProperty"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("TestClass", code, expected);
    }

    [Fact]
    public void RobustnessTest_EqualityCheckAttribute_MissingArguments_DoesNotCrash()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class TestClass
                            {
                                [EqualityCheck]
                                [GenerateProperties]
                                private double _myProperty;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class TestClass
                                {
                                    public double MyProperty
                                    {
                                        get => _myProperty;
                                        set
                                        {
                                            if (value.Equals(_myProperty)) return;
                                            _myProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("TestClass", code, expected);
    }

    [Fact]
    public void RobustnessTest_PropertyAttributeAttribute_MissingArguments_DoesNotCrash()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class TestClass
                            {
                                [PropertyAttribute]
                                [GenerateProperties]
                                private int _myProperty;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class TestClass
                                {
                                    public int MyProperty
                                    {
                                        get => _myProperty;
                                        set
                                        {
                                            if (value.Equals(_myProperty)) return;
                                            _myProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("TestClass", code, expected, [(6,6,"CS7036")]);
    }
    
    
    [Fact]
    public void DefaultValueAsString_OnPartialProperty_GeneratesCorrectExpression()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class TestClass
                            {
                                [DefaultValueAsString("new object()")]
                                public partial object MyObject { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class TestClass
                                {
                                    private object? ___myObject = new object();
                                    public partial object? MyObject
                                    {
                                        get => ___myObject;
                                        set
                                        {
                                            if (value is null && ___myObject is null || (value?.Equals(___myObject) ?? false)) return;
                                            ___myObject = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("TestClass", code, expected);
    }
    
    [Fact]
    public void PartialPropertyWithDefaultValue_GeneratesBackingField()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class PartialPropertyWithDefaultValue
                            {
                                [DefaultValue<string>("")]
                                public partial string PartialProperty { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class PartialPropertyWithDefaultValue
                                {
                                    private string? ___partialProperty = "";
                                    public partial string? PartialProperty
                                    {
                                        get => ___partialProperty;
                                        set
                                        {
                                            if (value is null && ___partialProperty is null || (value?.Equals(___partialProperty) ?? false)) return;
                                            ___partialProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PartialPropertyWithDefaultValue", code, expected);
    }

    [Fact]
    public void PartialPropertyWithArrayDefaultValue_HandlesEmptyArray()
    {
        const string code = """
                            #nullable enable
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class PartialPropertyWithArrayDefaultValue
                            {
                                [DefaultValue<string[]>([])]
                                public partial string[] PartialProperty { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class PartialPropertyWithArrayDefaultValue
                                {
                                    private string[] ___partialProperty = new string[] {  };
                                    public partial string[] PartialProperty
                                    {
                                        get => ___partialProperty;
                                        set
                                        {
                                            if (value.Equals(___partialProperty)) return;
                                            ___partialProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PartialPropertyWithArrayDefaultValue", code, expected);
    }

    [Fact]
    public void PartialPropertyWithNullableArrayDefaultValue_HandlesNullable()
    {
        const string code = """
                            #nullable enable
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GeneratePropertiesAttribute]
                            public partial class PartialPropertyWithNullableArrayDefaultValue
                            {
                                public partial string[]? PartialProperty { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class PartialPropertyWithNullableArrayDefaultValue
                                {
                                    private string[]? ___partialProperty;
                                    public partial string[]? PartialProperty
                                    {
                                        get => ___partialProperty;
                                        set
                                        {
                                            if (value is null && ___partialProperty is null || (value?.Equals(___partialProperty) ?? false)) return;
                                            ___partialProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PartialPropertyWithNullableArrayDefaultValue", code, expected);
    }

    [Fact]
    public void PartialPropertyWithArrayDefaultValueWithValues_HandlesInitializedArray()
    {
        const string code = """
                            #nullable enable
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class PartialPropertyWithArrayDefaultValueWithValues
                            {
                                [DefaultValue<string[]>(["A", "B"])]
                                public partial string[] PartialProperty { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class PartialPropertyWithArrayDefaultValueWithValues
                                {
                                    private string[] ___partialProperty = new string[] { "A", "B" };
                                    public partial string[] PartialProperty
                                    {
                                        get => ___partialProperty;
                                        set
                                        {
                                            if (value.Equals(___partialProperty)) return;
                                            ___partialProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PartialPropertyWithArrayDefaultValueWithValues", code, expected);
    }
    [Fact]
    public void GuardAttribute_WithMissingArguments_DoesNotCrashTheGenerator()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel;
                            namespace TestNamespace;

                            public partial class TestClass : INotifyPropertyChanged, INotifyPropertyChanging
                            {
                                public event PropertyChangedEventHandler? PropertyChanged;
                                public event PropertyChangingEventHandler? PropertyChanging;

                                [Guard]
                                [PropertyAttribute]
                                [EqualityCheck]
                                [NotifyPropertyChanged]
                                [NotifyPropertyChanging]
                                [ValidationStrategy]
                                [PropertyName]
                                [PropertyEncapsulation]
                                private string? _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel;

                                namespace TestNamespace;
                                partial class TestClass
                                {
                                    public string? Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value is null && _field is null || (value?.Equals(_field) ?? false)) return;
                                            this.PropertyChanging?.Invoke(this, new System.ComponentModel.PropertyChangingEventArgs("Field"));
                                            _field = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("TestClass", code, expected, [
            (10, 6, "CS7036"), // GuardAttribute (missing methodName)
            (11, 6, "CS7036"), // PropertyAttribute (missing name)
            (16, 6, "CS7036"), // PropertyNameAttribute (missing name)
        ]);
    }
}
