using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class PartialPropertyTests
{
    [Fact]
    public void DefaultValueAsString_OnPartialProperty_GeneratesCorrectExpression()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class TestClass
                            {
                                [DefaultValueAsString("new object()")]
                                public partial object MyObject { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class TestClass
                                {
                                    private object? ___myObject = new object();
                                    public partial object? MyObject
                                    {
                                        get => ___myObject;
                                        set
                                        {
                                            if (value is null && ___myObject is null || (value?.Equals(___myObject) ?? false)) return;
                                            ___myObject = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("TestClass", code, expected);
    }
    
    [Fact]
    public void PartialPropertyWithDefaultValue_GeneratesBackingField()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class PartialPropertyWithDefaultValue
                            {
                                [DefaultValue<string>("")]
                                public partial string PartialProperty { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class PartialPropertyWithDefaultValue
                                {
                                    private string? ___partialProperty = "";
                                    public partial string? PartialProperty
                                    {
                                        get => ___partialProperty;
                                        set
                                        {
                                            if (value is null && ___partialProperty is null || (value?.Equals(___partialProperty) ?? false)) return;
                                            ___partialProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PartialPropertyWithDefaultValue", code, expected);
    }

    [Fact]
    public void PartialPropertyWithArrayDefaultValue_HandlesEmptyArray()
    {
        const string code = """
                            #nullable enable
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class PartialPropertyWithArrayDefaultValue
                            {
                                [DefaultValue<string[]>([])]
                                public partial string[] PartialProperty { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class PartialPropertyWithArrayDefaultValue
                                {
                                    private string[] ___partialProperty = new string[] {  };
                                    public partial string[] PartialProperty
                                    {
                                        get => ___partialProperty;
                                        set
                                        {
                                            if (value.Equals(___partialProperty)) return;
                                            ___partialProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PartialPropertyWithArrayDefaultValue", code, expected);
    }

    [Fact]
    public void PartialPropertyWithNullableArrayDefaultValue_HandlesNullable()
    {
        const string code = """
                            #nullable enable
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GeneratePropertiesAttribute]
                            public partial class PartialPropertyWithNullableArrayDefaultValue
                            {
                                public partial string[]? PartialProperty { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class PartialPropertyWithNullableArrayDefaultValue
                                {
                                    private string[]? ___partialProperty;
                                    public partial string[]? PartialProperty
                                    {
                                        get => ___partialProperty;
                                        set
                                        {
                                            if (value is null && ___partialProperty is null || (value?.Equals(___partialProperty) ?? false)) return;
                                            ___partialProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PartialPropertyWithNullableArrayDefaultValue", code, expected);
    }

    [Fact]
    public void PartialPropertyWithArrayDefaultValueWithValues_HandlesInitializedArray()
    {
        const string code = """
                            #nullable enable
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class PartialPropertyWithArrayDefaultValueWithValues
                            {
                                [DefaultValue<string[]>(["A", "B"])]
                                public partial string[] PartialProperty { get; set; }
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class PartialPropertyWithArrayDefaultValueWithValues
                                {
                                    private string[] ___partialProperty = new string[] { "A", "B" };
                                    public partial string[] PartialProperty
                                    {
                                        get => ___partialProperty;
                                        set
                                        {
                                            if (value.Equals(___partialProperty)) return;
                                            ___partialProperty = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PartialPropertyWithArrayDefaultValueWithValues", code, expected);
    }
}
