using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class PropertyEncapsulationTests
{
    [Fact]
    public void PropertyEncapsulation_GeneratesVariousAccessModifiers()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class PropertyEncapsulation
                            {
                                [PropertyEncapsulation(EPropertyEncapsulation.Public)]
                                private int _publicField;

                                [PropertyEncapsulation(EPropertyEncapsulation.Protected)]
                                private int _protectedField;

                                [PropertyEncapsulation(EPropertyEncapsulation.Private)]
                                private int _privateField;

                                [PropertyEncapsulation(EPropertyEncapsulation.Internal)]
                                private int _internalField;

                                [PropertyEncapsulation(EPropertyEncapsulation.ProtectedInternal)]
                                private int _protectedInternalField;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class PropertyEncapsulation
                                {
                                    public int Public
                                    {
                                        get => _publicField;
                                        set
                                        {
                                            if (value.Equals(_publicField)) return;
                                            _publicField = value;
                                        }
                                    }
                                    protected int Protected
                                    {
                                        get => _protectedField;
                                        set
                                        {
                                            if (value.Equals(_protectedField)) return;
                                            _protectedField = value;
                                        }
                                    }
                                    private int Private
                                    {
                                        get => _privateField;
                                        set
                                        {
                                            if (value.Equals(_privateField)) return;
                                            _privateField = value;
                                        }
                                    }
                                    internal int Internal
                                    {
                                        get => _internalField;
                                        set
                                        {
                                            if (value.Equals(_internalField)) return;
                                            _internalField = value;
                                        }
                                    }
                                    protected internal int ProtectedInternal
                                    {
                                        get => _protectedInternalField;
                                        set
                                        {
                                            if (value.Equals(_protectedInternalField)) return;
                                            _protectedInternalField = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("PropertyEncapsulation", code, expected);
    }
}
