using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class SetterGetterModeTests
{
    [Fact]
    public void SetterModeDefault_OnNonReadOnlyField_GeneratesSetAccessor()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class SetterModeNoReadOnlyDefault
                            {
                                [Setter(ESetterMode.Default)]
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class SetterModeNoReadOnlyDefault
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("SetterModeNoReadOnlyDefault", code, expected);
    }

    [Fact]
    public void SetterModeDefault_OnReadOnlyField_GeneratesInitAccessor()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class SetterModeReadOnlyDefault
                            {
                                [Setter(ESetterMode.Default)]
                                private readonly float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class SetterModeReadOnlyDefault
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        init
                                        {
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("SetterModeReadOnlyDefault", code, expected);
    }

    [Fact]
    public void SetterModeSet_OnReadOnlyField_GeneratesSetAccessor()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class SetterModeReadOnlySet
                            {
                                [Setter(ESetterMode.Set)]
                                private readonly float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class SetterModeReadOnlySet
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("SetterModeReadOnlySet", code, expected, ["CS0191"]);
    }

    [Fact]
    public void SetterModeInit_OnNonReadOnlyField_GeneratesInitAccessor()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class SetterModeNoReadOnlyInit
                            {
                                [Setter(ESetterMode.Init)]
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class SetterModeNoReadOnlyInit
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        init
                                        {
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("SetterModeNoReadOnlyInit", code, expected);
    }

    [Fact]
    public void SetterModeNone_GeneratesGetterOnly()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class SetterModeNone
                            {
                                [Setter(ESetterMode.None)]
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class SetterModeNone
                                {
                                    public float Field
                                    {
                                        get => _field;
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("SetterModeNone", code, expected);
    }

    [Fact]
    public void GetterModeDefault_GeneratesGetter()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class GetterModeDefault
                            {
                                [Getter(EGetterMode.Default)]
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class GetterModeDefault
                                {
                                    public float Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("GetterModeDefault", code, expected);
    }

    [Fact]
    public void GetterModeNone_GeneratesSetterOnly()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [GenerateProperties]
                            public partial class GetterModeNone
                            {
                                [Getter(EGetterMode.None)]
                                private float _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class GetterModeNone
                                {
                                    public float Field
                                    {
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("GetterModeNone", code, expected);
    }
}
