using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class ValidationTests
{
    [Fact]
    public void MaxLengthValidation_GeneratesLengthCheck()
    {
        const string code = """
                            #nullable enable
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class MaxLengthValidation
                            {
                                [ValidationStrategy(EValidationStrategy.Exception), MaxLength(123)]
                                private string _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class MaxLengthValidation
                                {
                                    [System.ComponentModel.DataAnnotations.MaxLengthAttribute(123)]
                                    public string Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (value.Length > 123)
                                                throw new System.ArgumentException("Validation of Field failed: Value must be at most 123 characters long", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("MaxLengthValidation", code, expected);
    }

    [Fact]
    public void IntRangeValidation_GeneratesRangeCheck()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class IntRangeValidation
                            {
                                [ValidationStrategy(EValidationStrategy.Exception), Range(5, 6)]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class IntRangeValidation
                                {
                                    [System.ComponentModel.DataAnnotations.RangeAttribute(5, 6)]
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (value < 5 || value > 6)
                                                throw new System.ArgumentException("Validation of Field failed: Value must be between 5 and 6", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("IntRangeValidation", code, expected);
    }

    [Fact]
    public void DoubleRangeValidation_GeneratesRangeCheck()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class DoubleRangeValidation
                            {
                                [ValidationStrategy(EValidationStrategy.Exception), Range(5.1, 6.1)]
                                private double _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class DoubleRangeValidation
                                {
                                    [System.ComponentModel.DataAnnotations.RangeAttribute(5.1, 6.1)]
                                    public double Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (value < 5.1 || value > 6.1)
                                                throw new System.ArgumentException("Validation of Field failed: Value must be between 5.1 and 6.1", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("DoubleRangeValidation", code, expected);
    }

    [Fact]
    public void ExplicitTypeRangeValidation_UsesCompareTo()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            using System.ComponentModel.DataAnnotations;
                            namespace TestNamespace;

                            public partial class ExplicitTypeRangeValidation
                            {
                                [ValidationStrategy(EValidationStrategy.Exception), Range(typeof(int), "5", "6")]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;
                                using System.ComponentModel.DataAnnotations;

                                namespace TestNamespace;
                                partial class ExplicitTypeRangeValidation
                                {
                                    [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(int), "5", "6")]
                                    public int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            if (value.CompareTo(5) < 0 || value.CompareTo(6) > 0)
                                                throw new System.ArgumentException("Validation of Field failed: Value must be between 5 and 6", nameof(value));
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("ExplicitTypeRangeValidation", code, expected);
    }
}
