using X39.Roslyn.Property.Tests.TestHelpers;
using Xunit;

namespace X39.Roslyn.Property.Tests;

public class VirtualPropertyTests
{
    [Fact]
    public void VirtualPropertyAttribute_GeneratesVirtualProperty()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class BaseClass
                            {
                                [VirtualProperty]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class BaseClass
                                {
                                    public virtual int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("BaseClass", code, expected);
    }

    [Fact]
    public void VirtualPropertyWithNotifyPropertyChanged_GeneratesVirtualPropertyWithNotification()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            [NotifyPropertyChanged(true)]
                            public partial class BaseClass
                            {
                                [VirtualProperty]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class BaseClass
                                 : System.ComponentModel.INotifyPropertyChanged
                                {
                                    public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
                                    public virtual int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                            this.PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs("Field"));
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("BaseClass", code, expected);
    }

    [Fact]
    public void VirtualPropertyWithProtectedEncapsulation_GeneratesProtectedVirtualProperty()
    {
        const string code = """
                            using X39.Roslyn.Property;
                            namespace TestNamespace;

                            public partial class BaseClass
                            {
                                [VirtualProperty, PropertyEncapsulation(EPropertyEncapsulation.Protected)]
                                private int _field;
                            }
                            """;

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                using System;
                                using System.Collections.Generic;
                                using X39.Roslyn.Property;

                                namespace TestNamespace;
                                partial class BaseClass
                                {
                                    protected virtual int Field
                                    {
                                        get => _field;
                                        set
                                        {
                                            if (value.Equals(_field)) return;
                                            _field = value;
                                        }
                                    }
                                }

                                """;

        GeneratorTestHelper.VerifyGeneratedCode("BaseClass", code, expected);
    }
}
